src/Entity/Client.php
<?php

namespace App\Entity;

use App\Entity\City;
use App\Entity\ClientType;
use App\Entity\Contact;
use App\Entity\Country;
use App\Entity\Street;
use App\Entity\User;
use App\Repository\ClientRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Client entity.
 */
#[ORM\Entity(repositoryClass: ClientRepository::class)]
#[ORM\Table(name: 'v6__clients')]
class Client
{

    /**
     * Identifier of the Client.
     *
     * @var int
     */
    #[ORM\Id]
    #[ORM\Column(type: "integer")]
    #[ORM\GeneratedValue]
    protected int $id;

    /**
     * Many clients belong to one type.
     *
     * @var ClientType|null
     */
    #[ORM\ManyToOne(targetEntity: ClientType::class)]
    #[ORM\JoinColumn(name: "type_id", referencedColumnName: "id")]
    protected $type;

    /**
     * Client name.
     *
     * @var string
     */
    #[ORM\Column(type: "string", length: 48)]
    protected string $name;

    /**
     * Client's name note.
     *
     * @var string
     */
    #[ORM\Column(type: "string", length: 128)]
    protected string $name_note = '';

    /**
     * Client's LB number.
     *
     * @var string
     */
    #[ORM\Column(type: "string", length: 13)]
    protected string $lb;

    /**
     * Supplier flag.
     *
     * @var boolean
     */
    #[ORM\Column(type: "boolean")]
    protected bool $is_supplier;

    /**
     * Many Clients live in One Country.
     */
    #[ORM\ManyToOne(targetEntity: Country::class)]
    #[ORM\JoinColumn(name: "country_id", referencedColumnName: "id")]
    protected $country;

    /**
     * Many Clients live in One City.
     */
    #[ORM\ManyToOne(targetEntity: City::class)]
    #[ORM\JoinColumn(name: "city_id", referencedColumnName: "id")]
    protected $city;

    /**
     * Many Clients live in One Street.
     */
    #[ORM\ManyToOne(targetEntity: Street::class)]
    #[ORM\JoinColumn(name: "street_id", referencedColumnName: "id")]
    protected $street;

    /**
     * Client's home number.
     *
     * @var string
     */
    #[ORM\Column(type: "string", length: 8)]
    protected string $home_number = '';

    /**
     * Client's address note.
     *
     * @var string
     */
    #[ORM\Column(type: "string", length: 128)]
    protected string $address_note = '';

    /**
     * Client's note.
     *
     * @var string
     */
    #[ORM\Column(type: "text")]
    protected string $note = '';

    /**
     * Unidirectional - Many users have many contacts
     *
     * @var Collection
     */
    #[ORM\ManyToMany(targetEntity: Contact::class, inversedBy: 'clients', cascade: ['persist'])]
    #[ORM\JoinTable(
        name: 'v6__clients__contacts',
        joinColumns: [new ORM\JoinColumn(name: 'client_id', referencedColumnName: 'id')],
        inverseJoinColumns: [new ORM\JoinColumn(name: 'contact_id', referencedColumnName: 'id')]
    )]
    private Collection $contacts;

    /**
     * Date when the client was created.
     *
     * @var DateTime
     */
    #[ORM\Column(type: "datetime", options: ["default" => "CURRENT_TIMESTAMP"])]
    protected DateTime $created_at;

    /**
     * Many Clients have been created from One User.
     *
     * @var User
     */
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: "created_by_user_id", referencedColumnName: "id", nullable: false)]
    protected User $created_by_user;

    /**
     * Date when the client was modified.
     *
     * @var DateTime
     */
    #[ORM\Column(type: "datetime", options: ["default" => "CURRENT_TIMESTAMP"])]
    protected DateTime $modified_at;

    /**
     * Many Clients have been updated from One User.
     *
     * @var int
     */
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: "modified_by_user_id", referencedColumnName: "id")]
    protected $modified_by_user;

    public function __construct()
    {
        $this->contacts = new ArrayCollection();
        $this->name_note = '';
        $this->lb = '';
        $this->home_number = '';
        $this->address_note = '';
        $this->note = '';
        $this->created_at = new DateTime();
        $this->modified_at = new DateTime();
    }

    public function getId() {
        return $this->id;
    }

    public function setType(?ClientType $type): void
    {
        $this->type = $type;
    }

    public function getType(): ?ClientType
    {
        return $this->type;
    }

    public function setName($name) {
        $this->name = $name;
    }

    public function getName() {
        return $this->name;
    }

    public function setNameNote($name_note) {
        $this->name_note = $name_note === null ? '' : $name_note;
    }

    public function getNameNote() {
        return $this->name_note;
    }

    public function setLb($lb) {
        $this->lb = $lb === null ? '' : $lb;
    }

    public function getLb() {
        return $this->lb;
    }

    public function setIsSupplier($is_supplier) {
        $this->is_supplier = $is_supplier;
    }

    public function getIsSupplier() {
        return $this->is_supplier;
    }

    public function setCountry($country) {
        $this->country = $country;
    }

    public function getCountry() {
        return $this->country;
    }

    public function setCity($city) {
        $this->city = $city;
    }

    public function getCity() {
        return $this->city;
    }

    public function setStreet($street) {
        $this->street = $street;
    }

    public function getStreet() {
        return $this->street;
    }

    public function setHomeNumber($home_number) {
        $this->home_number = $home_number === null ? '' : $home_number;
    }

    public function getHomeNumber() {
        return $this->home_number;
    }

    public function setAddressNote($address_note) {
        $this->address_note = $address_note === null ? '' : $address_note;
    }

    public function getAddressNote() {
        return $this->address_note;
    }

    public function setNote($note) {
        $this->note = $note === null ? '' : $note;
    }

    public function getNote() {
        return $this->note;
    }

    public function getContacts() {
        return $this->contacts;
    }

    public function setContacts($contacts)
    {
        $this->contacts = $contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
        }
        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        $this->contacts->removeElement($contact);
        return $this;
    }

    public function setCreatedAt(\DateTime $created_at) {
        $this->created_at = $created_at;
    }

    public function getCreatedAt() {
        return $this->created_at;
    }

    public function setCreatedByUser($created_by_user) {
        $this->created_by_user = $created_by_user;
    }

    public function getCreatedByUser() {
        return $this->created_by_user;
    }

    public function setModifiedAt(\DateTime $modified_at) {
        $this->modified_at = $modified_at;
    }

    public function getModifiedAt() {
        return $this->modified_at;
    }

    public function setModifiedByUser($modified_by_user) {
        $this->modified_by_user = $modified_by_user;
    }

    public function getModifiedByUser() {
        return $this->modified_by_user;
    }
  
}

src/Entity/ClientType.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ClientType entity.
 */
#[ORM\Entity]
#[ORM\Table(name: 'v6__client__types')]
class ClientType
{

    /**
     * Identifier of the ClientType.
     *
     * @var int
     */
    #[ORM\Id]
    #[ORM\Column(type: "integer")]
    #[ORM\GeneratedValue]
    protected $id;

    /**
     * ClientType's name.
     *
     * @var string
     */
    #[ORM\Column(type: "string", length: 48)]
    protected $name;

    public function getId() {
        return $this->id;
    }

    public function setName($name) {
        $this->name = $name;
    }

    public function getName() {
        return $this->name;
    }

}

src/Controller/Client/Client.class.php
<?php
require_once filter_input(INPUT_SERVER, 'DOCUMENT_ROOT') . '/autoload.php';
/**
 * Client class
 *
 * @author Dragan Jancikin <dragan.jancikin@gmail.com>
 */
class Client extends Database {

    protected $id;
    protected $vps_id;
    protected $name;
    protected $name_note;
    protected $lb;
    protected $is_supplier;
    protected $state_id;
    protected $city_id;
    protected $street_id;
    protected $home_number;
    protected $address_note;
    protected $note;
    protected $created_at_date;
    protected $created_at_user_id;
    protected $modified_at_date;
    protected $modified_at_user_id;

    /**
     * Method that return client types
     * 
     * @return array
     */
    public function getVpses() {
        return array(
            array('id'=>'1', 'name'=>'Fizičko lice'),
            array('id'=>'2', 'name'=>'Pravno lice')
        );
    }

    /**
     * Method that return all states from table state
     * 
     * @return array
     */
    public function getStates() {
        $result = $this->get("SELECT * FROM state ORDER BY name");
        return $result;
    }

    /**
     * Method that return all citys from table city
     * 
     * @return array
     */
    public function getCitys() {
        $result = $this->get("SELECT * FROM city ORDER BY name");
        return $result;
    }

    /**
     * Method that return city by ID
     * 
     * @param integer $id
     * 
     * @return array
     */
    public function getCity($id) {
        $result =  $this->get("SELECT * FROM city WHERE id = $id");
        return ( empty($result[0]) ? false : $result[0] );
    }

    /**
     * Method that return all streets from table street
     * 
     * @return array
     */
    public function getStreets() {
        $result = $this->get("SELECT * FROM street ORDER BY name");
        return $result;
    }

    /**
     * Method that return all client with name or name_note like $name
     * 
     * @param string $name
     * 
     * @return array
     */
    public function search($name) {
        $result = $this->get("SELECT client.id, client.name, client.name_note, state.name as state_name, city.name as city_name, street.name as street_name, client.home_number "
                            . "FROM client "
                            . "JOIN (street, city, state) "
                            . "ON (client.state_id = state.id AND client.city_id = city.id AND client.street_id = street.id ) "
                            . "WHERE (client.name LIKE '%$name%' OR client.name_note LIKE '%$name%') "
                            . "ORDER BY client.name");
        return $result;
    }

    /**
     * Method that return client data by client ID
     * 
     * @param integer $id
     * 
     * @return array
     */
    public function getClient($id) {
        $result =  $this->get("SELECT client.id, client.vps_id, client.name, client.name_note, client.lb, client.is_supplier, client.state_id, client.city_id, client.street_id, state.name as state_name, city.name as city_name, street.name as street_name, client.home_number, client.address_note, client.note "
                            . "FROM client "
                            . "JOIN (street, city, state)"
                            . "ON (client.state_id = state.id AND client.city_id = city.id AND client.street_id = street.id )"
                            . "WHERE client.id = $id ");
        if(empty($result)) {
            die('<script>location.href = "/clients/" </script>');
        } else {
            ($result[0]['vps_id'] == 1 ? $result[0]['vps_name'] = "Fizičko lice" : $result[0]['vps_name'] = "Pravno lice" );
            return $result[0];
        }
    }

    /**
     * Method that return all clients from table client
     * 
     * @return array
     */
    public function getClients() {
        $result = $this->get("SELECT client.id, client.vps_id, client.name, city.name as city_name "
                            . "FROM client "
                            . "JOIN (city) "
                            . "ON (client.city_id = city.id) "
                            . "ORDER BY name");
        return $result;
    }
    
    /**
     * Method that return all suppliers from table client
     * 
     * @return array
     */
    public function getSuppliers() {
        $result = $this->get("SELECT id, name, is_supplier FROM client WHERE is_supplier = 1 ORDER BY name");
        return $result;
    }
    
    /**
     * Method that return last clients
     * 
     * @param integer $limit
     * 
     * @return array
     */
    public function getLastClients($limit){
        $result = $this->get("SELECT client.id, client.name, client.name_note, state.name as state_name, city.name as city_name, street.name as street_name, client.home_number "
                        . "FROM client "
                        . "JOIN (street, city, state)"
                        . "ON (client.state_id = state.id AND client.city_id = city.id AND client.street_id = street.id )"
                        . "ORDER BY client.id DESC LIMIT $limit");
        return $result;
    }

    /**
     * 
     */
    public function checkGetClient($id = FALSE){
        if($id) {
            $new = preg_replace('/[^0-9]/', '', $id);
            return $new;
        } else {
            die('<script>location.href = "/clients/" </script>');
        }
    }

}





/*
class Products extends DbConnect {

    protected $id;
    protected $sku;
    protected $name;
    protected $price;
    protected $type;
    protected $attributes;

    

    public function select() {
        $query = "SELECT * FROM products";
        $result = $this->connect()->query($query);

        $row = $result->fetch(PDO::FETCH_ASSOC);
        $this->id = $row['Id'];
        $this->sku = $row['SKU'];
        $this->name = $row['Name'];
        $this->price = $row['Price'];
        $this->type = $row['Type'];
        $this->attributes = $row['Attributes'];
    }

    public function getId() {
        return $this->id;
    }

    public function getSKU() {
        return $this->sku;
    }

    public function getName() {
        return $this->name;
    }

    public function getPrice() {
        return $this->price;
    }

    public function getType() {
        return $this->type;
    }

    public function getAttributes() {
        return $this->attributes;
    }

}



PHP

class Person{
    private $firstname = null;
    public function setFirstName($aFirstName){
         $this->firstname = $aFirstName;
    }

    public function getFirstName(){
         return $this->firstname;
    }
}

$person = new Person();

if(isset($_POST['submit'])){
    $person->setFirstName($_POST['firstname']);
}
HTML

<form action="" method="post">
    First Name: <input type="text" name="firstname" value="<?php if($person->getFirstName() != null){ echo $person->getFirstName(); } ?>"/>
    <input type="submit" name="submit" value="Submit" />
</form>
*/

src/Controller/Client/Contact.class.php
<?php
require_once filter_input(INPUT_SERVER, 'DOCUMENT_ROOT') . '/autoload.php';
/**
 * Contact class
 * 
 * @author Dragan Jancikin <dragan.jancikin@gmail.com>
 */
class Contact extends Database {

    protected $id;
    protected $client_id;
    protected $type_id;
    protected $number;
    protected $note;


    /**
     * Method that return contacts by Client ID
     * 
     * @param integer $client_id
     * 
     * @return array
     * 
     * @author Dragan Jancikin <dragan.jancikin@gmail.com>
     */
    public function getContactsById($client_id){
        $result = $this->get("SELECT client_contacts.contact_id, contacts.id, contacts.type_id, contacts.number, contacts.note, contacttypes.id, contacttypes.name "
                            . "FROM client_contacts "
                            . "JOIN (contacts, contacttypes)"
                            . "ON (client_contacts.contact_id = contacts.id AND contacts.type_id = contacttypes.id )"
                            . "WHERE client_contacts.client_id = $client_id "
                            . "ORDER BY contacttypes.id ");
        return $result;
    }


    /**
     * Method that return all contact types form table contacttypes
     * 
     * @return array
     * 
     * @author Dragan Jancikin <dragan.jancikin@gmail.com>
     */
    public function getContactTypes (){
        return $this->get("SELECT * FROM contacttypes");
    }


    /**
     * Method that delete contact from client
     * 
     * @param integer $client_id
     * @param integer $contact_id
     * 
     * @author Dragan Jancikin <dragan.jancikin@gmail.com>
     */
    public function delContact($client_id, $contact_id){
        $this->delete("DELETE FROM contacts WHERE id='$contact_id' ");
        $this->delete("DELETE FROM client_contacts WHERE contact_id='$contact_id' ");
        die('<script>location.href = "?view&client_id='.$client_id.'" </script>');
    }

}

templates/client/city_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit City{% endblock %}

{% block body %}
    {% include 'client/tools_menu.html.twig' %}
    <div class="col-sm-12 col-md-11 col-lg-9 col-xl-7 px-2">
        <div class="card mb-4 shadow-sm">
            <div class="card-header p-2">Izmena podataka o naselju:</div>
            <div class="card-body">
                {% include 'client/form/city.html.twig' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/client/client_view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block body %}
    {% include 'client/tools_menu.html.twig' %}
    <div class="col-sm-12 col-md-11 col-lg-9 col-xl-7 px-2">
        {% include 'client/form/client_view.html.twig' %}
    </div>
    {% include 'client/modals.html.twig' %}
{% endblock %}

templates/client/country_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block body %}
    {% include 'client/tools_menu.html.twig' %}
    <div class="col-sm-12 col-md-11 col-lg-9 col-xl-7 px-2">
        <div class="card mb-4 shadow-sm">
            <div class="card-header p-2">Izmena podataka o državi:</div>
            <div class="card-body">
                {% include 'client/form/country.html.twig' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/client/country_view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Country Details{% endblock %}

{% block body %}
    {% include 'client/tools_menu.html.twig' %}
    <div class="col-sm-12 col-md-11 col-lg-9 col-xl-7 px-2">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                Drzava info
            </div>
            <div class="card-body pt-2">
                {% include 'client/table/country_view.html.twig' %}
            </div>
            <div class="card-footer">
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="/countries/new" class="btn btn-sm btn-outline-secondary">
                        <i class="fas fa-arrow-left"></i> Lista država</a>
                    <a href="/countries/{{ country.id }}/edit" class="btn btn-sm btn-primary">
                        <i class="fas fa-edit"></i> Izmeni državu
                    </a>
                    {% if allow_to_delete %}
                    <a href="/countries/{{ country.id }}/delete" class="btn btn-sm btn-danger"
                       onclick="return confirm('Da li ste sigurni da želite da obrišete ovu državu?');">
                        <i class="fas fa-trash-alt"></i> Obriši državu
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-11 col-lg-9 col-xl-7 px-2">
        <div class="card shadow-sm">
            <div class="card-header">
                Lista klijenata iz: {{ country.name }}
            </div>
            <div class="card-body pt-2">
        {% include 'client/table/clients_where_country_use.html.twig' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/client/form_edit_client.html.twig
<!-- Edit Client Data -->
<div class="card mb-4">
    <div class="card-header p-2">
        <h6 class="m-0 text-dark">
          Izmena podataka o klijentu: <strong>{{ client.name }}</strong>
        </h6>
    </div>

    <div class="card-body px-2">
        <form action="/client/{{ client.id }}/edit " method="post">
            <input type="hidden" name="client_id" value="<?php echo $client_id ?>">
            <input type="hidden" name="type_id" value="<?php echo $client['type_id'] ?>">

            <div class="row mb-2">
                <label for="selectTip" class="col-sm-3 col-form-label text-left text-sm-right">Vrsta klijenta:</label>
                <div class="col-sm-4">
                    <select id="selectTip" class="form-select form-select-sm" name="type_id" >
                        <option value="{{ client.type_id }}">{{ client.type }}</option>
                        {% for type in client_types %}
                        <option value="{{ type.id }}">
                            {{ type.name }}
                        </option>
                        {% endfor %}
                     </select>
                </div>
            </div>

            <div class="row mb-2">
                <label for="inputName" class="col-sm-3 col-form-label text-left text-sm-right">Naziv:</label>
                <div class="col-sm-9 mb-2">
                    <input class="form-control form-control-sm" id="inputName" type="text" name="name"
                           value="{{ client.name }}" >
                </div>
                <div class="col-sm-9 offset-sm-3">
                    <input class="form-control form-control-sm" id="inputName" type="text" name="name_note"
                           value="{{ client.name_note }}" title="Beleška uz naziv klijenta">
                </div>
            </div>

            {% if client.type_id == 2 %}
            <div class="row mb-2">
                <label for="inputPIB" class="col-sm-3 col-form-label text-left text-sm-right">PIB: </label>
                <div class="col-sm-4">
                    <input class="form-control form-control-sm" id="inputPIB" type="text" name="lb"
                           value="{{ client.lb }}" maxlength="9" >
                </div>
            </div>
            {% endif %}

            <div class="row mb-2">
                <label for="is_supplier" class="col-sm-3 col-form-label text-left text-sm-right">Dobavljač:</label>
                <div class="col-sm-3">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="is_supplier" name="is_supplier" value="1"
                               {% if client.is_supplier %}checked{% endif %} >
                        <label class="form-check-label" for="is_supplier">Jeste</label>
                    </div>
                </div>
            </div>

            <div class="row mb-2">
                <label for="selectCountry" class="col-sm-3 col-form-label text-left text-sm-right">Država:</label>
                <div class="col-sm-5">
                    <select id="selectCountry" class="form-select form-select-sm" name="country_id">
                        {% if not client.country %}
                            <option>Izaberite drzavu</option>
                        {% else %}
                            <option value="{{ client.country_id }}">{{ client.country }}</option>
                        {% endif %}

                        {% for country in countries %}
                            <option value="{{ country.id }}">{{ country.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="row mb-2">
                <label for="selectCity" class="col-sm-3 col-form-label text-left text-sm-right">Naselje:</label>
                <div class="col-sm-5">
                    <select id="selectCity" class="form-select form-select-sm" name="city_id">
                        {% if not client.city %}
                            <option>Izaberite naselje</option>
                        {% else %}
                            <option value="{{ client.city_id }}">{{ client.city }}</option>
                        {% endif %}

                        {% for city in cities %}
                            <option value="{{ city.id }}">{{ city.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="row mb-2">
                <label for="selectStreet" class="col-sm-3 col-form-label text-left text-sm-right">Ulica:</label>
                <div class="col-sm-5">
                    <select id="selectStreet" class="form-select form-select-sm" name="street_id">>
                        {% if not client.street %}
                            <option>Izaberite ulicu</option>
                        {% else %}
                            <option value="{{ client.street_id }}">{{ client.street }}</option>
                        {% endif %}

                        {% for street in streets %}
                            <option value="{{ street.id }}">{{ street.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="row mb-2">
                <label for="inputNum" class="col-sm-3 col-form-label text-left text-sm-right">Broj:</label>
                <div class="col-sm-2 mb-2">
                    <input class="form-control form-control-sm" id="inputNum" type="text" name="home_number"
                           value="{{ client.home_number }}" >
                </div>
                <div class="col-sm-7">
                    <input class="form-control form-control-sm" id="inputNum" type="text" name="address_note"
                           value="{{ cllient.address_note }}"
                         title="Beleška uz adresu klijenta">
                </div>
            </div>

            <div class="row mb-2">
                <label for="inputNote" class="col-sm-3 col-form-label text-left text-sm-right">Beleška: </label>
                <div class="col-sm-9">
                  <textarea class="form-control form-control-sm" id="inputNote" rows="3" name="note">{{ client.note }}</textarea>
                </div>
            </div>

            <div class="row mb-2">
                <div class="col-sm-3 offset-sm-3">
                    <button type="submit" class="btn btn-sm btn-success" title="Snimi izmene podataka o klijentu!">
                      <i class="fas fa-save"></i> Snimi
                    </button>
                </div>
            </div>

      </form>
    </div> <!-- End of Card Body -->

    <div class="card-footer px-2">
        <p class="h5">Kontakti</p>
        {% for contact in client.contacts %}
            <form action="/client/{{ client.id }}/contact/{{ contact.id }}/editContact"
                  method="post">

                <div class="row mb-2">
                    <div class="col-sm-3">
                        <select class="form-select form-select-sm" name="contact_type_id">>
                            <option value="{{ contact.type.id }}">{{ contact.type.name }}</option>
                            {% for type in contact_types %}
                                <option value="{{ type.id }}">{{ type.name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="col-sm-3">
                        <input type="text" class="form-control form-control-sm" name="body" value="{{ contact.body }}"
                               placeholder="Unesi kontakt" >
                    </div>

                    <div class="col-sm-4">
                        <input type="text" class="form-control form-control-sm" name="note" value="{{ contact.note }}"
                               placeholder="Unesi belešku" >
                    </div>

                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-success btn-sm " title="Snimi izmenu kontakta!">
                          <i class="fas fa-save"></i>
                        </button>
                        <a onClick="javascript: return confirm('Da li ste sigurni da želite da obrišete kontakt?');"
                           href="/client/{{ client.id }}/contact/{{ contact.id }}/removeContact"
                           class="btn btn-danger btn-sm "
                           title="Obriši kontakt!">
                          <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
            </form>
        {% endfor %}
    </div><!-- End of Card Body -->

</div><!-- End of Card -->

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block body %}
    {% include 'client/tools_menu.html.twig' %}

    <div class="col-lg-12 col-xl-10 px-2">
        <div class="card mb-4 shadow-sm">
            <div class="card-header p-2">
                <h6 class="m-0 font-weight-bold text-primary">Klijenti</h6>
            </div>
            <div class="card-body p-2">
                <div class="table-responsive">
                    {% include 'client/table/clients.html.twig' %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/client/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block body %}
    {% include 'client/tools_menu.html.twig' %}

    <div class="card mb-4">
        <div class="card-header p-2">
            <h6 class="m-0 font-weight-bold text-primary">Pretraga klijenata</h6>
        </div>
        <div class="card-body p-2">
            <!-- Table with list of last client. -->
            <div class="table-responsive">
                <table class="dataTable table table-bordered table-hover" id="" width="100%" cellspacing="0">
                    <thead class="thead-light">
                    <tr>
                        <th>klijent</th>
                        <th>adresa</th>
                    </tr>
                    </thead>
                    <tfoot class="thead-light">
                    <tr>
                        <th>klijent</th>
                        <th>adresa</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for client in clients %}
                        <tr>
                            <td>
                                <a href="/clients/{{ client.id }}">
                                    {{ client.name }}
                                </a>
                            </td>
                            <td>
                                {{ client.street ? client.street.name : '' }} {{ client.homeNumber }}
                                {% if client.street and client.city %}, {% endif %}
                                {{ client.city ? client.city.name : '' }}
                                {% if client.city and client.country %}, {% endif %}
                                {{ client.country ? client.country.name : '' }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- End of Card body. -->
    </div>
{% endblock %}