src/Entity/Order.php
<?php

namespace App\Entity;

use App\Entity\Client;
use App\Entity\User;
use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: 'v6__orders')]
class Order
{

    #[ORM\Id]
    #[ORM\Column(type: "integer")]
    #[ORM\GeneratedValue]
    protected $id;

    /**
     * Ordinal number of the Order in the current year.
     *
     * @var int
     */
    #[ORM\Column(type: "integer")]
    protected $ordinal_num_in_year;

    /**
     * Date of the Order.
     *
     * @var DateTime
     */
      #[ORM\Column(type: "datetime", options: ["default" => "CURRENT_TIMESTAMP"])]
    protected $date;

    /**
     * Many Order belongs to the One Supplier.
     *
     * @var int
     */
    #[ORM\ManyToOne(targetEntity: Client::class)]
    #[ORM\JoinColumn(name: "supplier_id", referencedColumnName: "id")]
    protected $supplier;

    /**
     * Many Orders can belong to the One Project.
     *
     * @var int
     */

    #[ORM\ManyToOne(targetEntity: Project::class)]
    #[ORM\JoinColumn(name: "project_id", referencedColumnName: "id")]
    //  protected $project;


    /**
     * Order title.
     *
     * @var string
     */
    #[ORM\Column(type: "string", length: 196)]
    protected $title;

    /**
     * Flag indicating if the Order is archived.
     *
     * @var boolean
     */
    #[ORM\Column(type: "boolean", options: ["default" => false])]
    protected $is_archived;

    /**
     * Order status.
     *
     * Can be: 0 => 'draft', 1 => 'ordered', 2 => 'arrived' (0 => 'nacrt',
     * 1 => 'poručeno', 2 => 'stiglo').
     *
     * @var int
     */
    #[ORM\Column(type: "integer", options: ["default" => 0] )]
    protected $status;

    /**
     * Accounting Document note.
     *
     * @var string
     */
    #[ORM\Column(type: "text", nullable: true)]
    protected $note;

    /**
     * Date when the Order was created.
     *
     * @var DateTime
     */
    #[ORM\Column(type: "datetime", options: ["default" => "CURRENT_TIMESTAMP"])]
    protected $created_at;

    /**
     * Many orders can be created by one user.
     *
     * @var int
     */
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: "created_by_user_id", referencedColumnName: "id")]
    protected $created_by_user;

    /**
     * Date when the Order was last modified.
     *
     * @var DateTime
     */
    #[ORM\Column(type: "datetime", options: ["default" => "CURRENT_TIMESTAMP"])]
    protected $modified_at;

    /**
     * Many orders can be updated by one user.
     *
     * @var int
     */
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: "modified_by_user_id", referencedColumnName: "id")]
    protected $modified_by_user;

    public function getId() {
        return $this->id;
    }

    public function setOrdinalNumInYear($ordinal_num_in_year) {
        $this->ordinal_num_in_year = $ordinal_num_in_year;
    }

    public function getOrdinalNumInYear() {
        return $this->ordinal_num_in_year;
    }

    public function setDate($date) {
        $this->date = $date;
    }

    public function getDate() {
        return $this->date;
    }

    /*
    public function setProject($project) {
        $this->project = $project;
    }

    public function getProject() {
        return $this->project;
    }
    */

    public function setSupplier($supplier) {
        $this->supplier = $supplier;
    }

    public function getSupplier() {
        return $this->supplier;
    }

    public function setTitle($title) {
      $this->title = $title;
    }

    public function getTitle() {
        return $this->title;
    }

    public function setIsArchived($is_archived) {
        $this->is_archived = $is_archived;
    }

    public function getIsArchived() {
        return $this->is_archived;
    }

    public function setStatus($status) {
        $this->status = $status;
    }

    public function getStatus() {
        return $this->status;
    }

    public function setNote($note) {
        $this->note = $note;
    }

    public function getNote() {
        return $this->note;
    }

    public function setCreatedAt(\DateTime $created_at) {
        $this->created_at = $created_at;
    }

    public function getCreatedAt() {
        return $this->created_at;
    }

    public function setCreatedByUser($created_by_user) {
        $this->created_by_user = $created_by_user;
    }

    public function getCreatedByUser() {
        return $this->created_by_user;
    }

    public function setModifiedAt(\DateTime $modified_at) {
        $this->modified_at = $modified_at;
    }

    public function getModifiedAt() {
        return $this->modified_at;
    }

    public function setModifiedByUser($modified_by_user) {
        $this->modified_by_user = $modified_by_user;
    }

    public function getModifiedByUser() {
        return $this->modified_by_user;
    }

}

src/Controller/DocumentController.php
<?php

namespace App\Controller;

use App\Entity\AccountingDocument;
use App\Entity\AccountingDocumentArticle;
use App\Entity\AccountingDocumentArticleProperty;
use App\Entity\AccountingDocumentType as AccountingDocumentTypeEntity;
use App\Entity\Article;
use App\Entity\ArticleProperty;
use App\Entity\Client;
use App\Entity\CompanyInfo;
use App\Entity\Payment;
use App\Entity\PaymentType;
use App\Entity\Preferences;
use App\Entity\Project;
use App\Entity\User;
use App\Form\AccountingDocumentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use TCPDF;

/**
 * DocumentController class
 *
 * @author Dragan Jancikin <dragan.jancikin@gmail.com>
 */
class DocumentController extends AbstractController
{

    private EntityManagerInterface $em;
    private string $page = 'documents';
    private string $pageTitle = 'Dokumenti';
    protected string $stylesheet;

    /**
     * DocumentController constructor.
     *
     * @param EntityManagerInterface $em The entity manager for database interactions.
     */
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * Displays the documents index page.
     *
     * Checks if the user is logged in, retrieves recent proformas, delivery notes, and return receipts, and renders
     * the documents index view.
     *
     * @return Response The HTTP response object.
     */
    #[Route('/documents', name: 'documents_index', methods: ['GET'])]
    public function index(): Response
    {
        session_start();
        if (!isset($_SESSION['username'])) {
            return $this->redirectToRoute('login_form');
        }

        $data = $this->getDefaultData();
        $data += [
            'tools_menu' => [
                'document' => FALSE,
                'cash_register' => FALSE,
            ],
            'proformas' => $this->em->getRepository(AccountingDocument::class)->getLast(1, 0, 10),
            'delivery_notes' => $this->em->getRepository(AccountingDocument::class)->getLast(2, 0, 10),
            'return_receipts' => $this->em->getRepository(AccountingDocument::class)->getLast(4, 0, 10),
        ];

        return $this->render('document/index.html.twig', $data);
    }

    /**
     * Displays the form for creating a new accounting document.
     *
     * Checks if the user is logged in, retrieves optional client and project data, fetches the list of clients, and
     * renders the new document form view.
     *
     * @param Request $request The HTTP request object.
     *
     * @return Response The HTTP response object.
     */
    #[Route('/documents/new', name: 'documents_new_form', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        session_start();
        if (!isset($_SESSION['username'])) {
            return $this->redirectToRoute('login_form');
        }

        $document = new AccountingDocument();
        $user = $this->em->find(User::class, $_SESSION['user_id']);
        $document->setCreatedByUser($user);

        $form = $this->createForm(AccountingDocumentType::class);

        if ($request->query->get('client_id')) {
            $client = $this->em->find(Client::class, $request->query->get('client_id'));
            $form->get('client')->setData($client);
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $document->setDate(new \DateTime("now"));
            $document->setOrdinalNumInYear(0);
            $document->setTitle($form->get('title')->getData());
            $document->setIsArchived(0);

            $document->setType($form->get('type')->getData());
            $document->setClient($form->get('client')->getData());

            $noteValue = $form->get('note')->getData();
            $document->setNote($noteValue !== null ? $noteValue : '');

            $document->setCreatedAt(new \DateTime("now"));
            $document->setModifiedAt(new \DateTime("now"));

            $this->em->persist($document);
            $this->em->flush();

            $this->em->getRepository(AccountingDocument::class)->setOrdinalNumInYear($document->getId());

            if ($request->query->get('project_id')) {
                $project = $this->em->find(Project::class, $request->query->get('project_id'));
                $project->getAccountingDocuments()->add($document);
                $this->em->flush();
            }

            return $this->redirectToRoute('document_edit_form', ['id' => $document->getId()]);
        }

        $data = $this->getDefaultData();
        $data += [
            'tools_menu' => [
                'document' => FALSE,
                'cash_register' => FALSE,
            ],
            'form' => $form->createView(),
        ];

        return $this->render('document/new.html.twig', $data);
    }

    /**
     * Displays the details of a specific accounting document.
     *
     * Checks if the user is logged in, retrieves the accounting document and its related data (client, articles,
     * totals, payments, etc.), prepares navigation and financial summary, and renders the document details view.
     *
     * @param int $id The ID of the accounting document to display.
     *
     * @return Response The HTTP response object.
     */
    #[Route('/documents/{id}', name: 'document_show', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function show(int $id): Response
    {
        session_start();
        if (!isset($_SESSION['username'])) {
            return $this->redirectToRoute('login_form');
        }

        $document = $this->em->find(AccountingDocument::class, $id);

        $clientId = $document->getClient()->getId();
        $client = $this->em->getRepository(Client::class)->getClientData($clientId);

        $allArticles = $this->em->getRepository(Article::class)->findAll();

        [$documentType, $documentTag, $documentStyle] = $this->getDocumentTypeData($document->getType()->getId());

        $preferences = $this->em->find(Preferences::class, 1);
        $exchangeRate = $preferences->getKurs();

        $accountingDocumentArticlesData = $this->getAccountingDocumentArticlesData($id);

        $totalTaxBaseRsd = $this->getAccountingDocumentTotalTaxBaseRSD($id);
        $totalTaxAmountRsd = $this->getAccountingDocumentTotalTaxAmountRSD($id);

        $totalRsd = $totalTaxBaseRsd + $totalTaxAmountRsd;

        $previous = $this->em->getRepository(AccountingDocument::class)->getPrevious($id, $document->getType()->getId());

        $next = $this->em->getRepository(AccountingDocument::class)->getNext($id, $document->getType()->getId());

        $advancePaymentEur = $this->em->getRepository(AccountingDocument::class)->getAvans($id);
        $advancePaymentRsd = $advancePaymentEur * $exchangeRate;
        $incomeEur = $this->em->getRepository(AccountingDocument::class)->getIncome($id);
        $incomeRsd = $incomeEur * $exchangeRate;
        $remainingRsd = $totalRsd - $advancePaymentRsd - $incomeRsd;
        $remainingEur = ($totalRsd / $exchangeRate) - $advancePaymentEur - $incomeEur;

        $data = $this->getDefaultData();

        $data += [
            'tools_menu' => [
                'document' => TRUE,
                'view' => TRUE,
                'edit' => FALSE,
                'cash_register' => TRUE,
            ],
            'document' => $document,
            'document_type' => $documentType,
            'document_tag' => $documentTag,
            'document_style' => $documentStyle,
            'client' => $client,
            'all_articles' => $allArticles,
            'accounting_document_articles_data' => $accountingDocumentArticlesData,
            'previous' => $previous,
            'next' => $next,
            'advance_payment_eur' => $advancePaymentEur,
            'advance_payment_rsd' => $advancePaymentRsd,
            'income_eur' => $incomeEur,
            'income_rsd' => $incomeRsd,
            'total_tax_base_rsd' => $totalTaxBaseRsd,
            'total_tax_amount_rsd' => $totalTaxAmountRsd,
            'total_rsd' => $totalRsd,
            'total_eur' => $totalRsd / $exchangeRate,
            'remaining_rsd' => $remainingRsd,
            'remaining_eur' => $remainingEur,
        ];

        return $this->render('document/view.html.twig', $data);
    }

    /**
     * Displays the edit form for a specific accounting document.
     *
     * Checks if the user is logged in, retrieves the accounting document and its related data (client, articles,
     * totals, payments, etc.), prepares navigation, financial summary, and a list of clients, and renders the document edit view.
     *
     * @param int $id The ID of the accounting document to edit.
     *
     * @return Response The HTTP response object.
     */
    #[Route('/documents/{id}/edit', name: 'document_edit_form', methods: ['GET'])]
    public function edit(int $id): Response
    {
        session_start();
        if (!isset($_SESSION['username'])) {
            return $this->redirectToRoute('login_form');
        }

        $document = $this->em->find(AccountingDocument::class, $id);

        $clientId = $document->getClient()->getId();
        $client = $this->em->getRepository(Client::class)->getClientData($clientId);

        $allArticles = $this->em->getRepository(Article::class)->findAll();

        [$documentType, $documentTag, $documentStyle] = $this->getDocumentTypeData($document->getType()->getId());

        $preferences = $this->em->find(Preferences::class, 1);
        $exchangeRate = $preferences->getKurs();

        $accountingDocumentArticlesData = $this->getAccountingDocumentArticlesData($id);

        $totalTaxBaseRsd = $this->getAccountingDocumentTotalTaxBaseRSD($id);

templates/document/article_in_document_change.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block body %}
  {% include 'document/tools_menu.html.twig' %}
  <div class="col-lg-12 px-2">
    {% include 'document/form/article_in_document_change.html.twig' %}
  </div>
{% endblock %}

templates/document/cash_register.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block body %}
  {% include 'document/tools_menu.html.twig' %}
  <div class="col-lg-12 px-2">
    {% include 'document/table/cash_register.html.twig' %}
  </div>
  {% include 'document/modals_2.html.twig' %}
{% endblock %}

templates/document/document_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block body %}
    {% include 'document/tools_menu.html.twig' %}
    <div class="col-lg-12 px-2">
        {% include 'document/form/document_edit.html.twig' %}
    </div>
{% include 'document/modals.html.twig' %}
{% endblock %}

templates/document/modals.html.twig
<!-- Modal add Article to Accounting Document -->
<div class="modal" id="addArticle" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title">Dodavanje proizvoda u dokument</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="/documents/{{ document.id }}/articles/add" method="post" role="form">
                <input type="hidden" name="pidb_id" value="{{ document.id }}">

                <div class="modal-body">

                    <div class="row mb-2">
                        <label for="article" class="col-sm-3 col-form-label">Proizvod:</label>
                        <div class="col-sm-9">
                            <div id="first">
                                <select class="form-select form-select-sm" name="article_id" id="article">
                                  <option value="">izaberi proizvod</option>
                                  {% for article in all_articles %}
                                    <option value="{{ article.id }}">{{ article.name }}</option>
                                  {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <label for="note" class="col-sm-3 col-form-label">Dodatni opis:</label>
                        <div class="col-sm-9">
                          <input type="text" class="form-control form-control-sm" name="note" id="note" value=""
                                 placeholder="Upišite belešku" >
                        </div>
                    </div>

                    <div class="row mb-2">
                        <label for="pieces" class="col-sm-3 col-form-label">Komada:</label>
                        <div class="col-sm-4">
                          <input type="text" class="form-control form-control-sm" name="pieces" id="pieces" value=""
                                 placeholder="Unesite količinu" />
                        </div>
                    </div>

                    <div id="second"></div>

                    </div>
                    <!-- End Modal Body -->

                    <div class="modal-footer">
                        <button type="submit" class="btn btn-sm btn-primary" >Dodaj proizvod</button>
                    </div>

            </form>
        </div>
    </div>
</div>
<!-- End Modal -->

<!-- Modal addPayment -->
<div class="modal" id="addPayment" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title">Evidencija uplata</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="/documents/{{ document.id }}/add-payment" method="post" role="form">
                <input type="hidden" name="pidb_id" value="{{ document.id }}">
                <input type="hidden" name="client_id" value="{{ document.client.id }}">
                <div class="modal-body">

                    <div class="row mb-2">
                        <label for="pidb" class="col-sm-3 col-form-label">Dokument:</label>
                        <div class="col-sm-9">
                            <select class="form-select form-select-sm" name="pidb_id" id="pidb">
                                <option value="{{ document.id }}">
                                    {{ document_tag }}
                                    {{ '%04d'|format(document.getOrdinalNumInYear()) }}
                                    -
                                    {{ document.getCreatedAt().format('m') }}
                                    {{ document.client.name }}
                                </option>
                            </select>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <label for="transaction_type" class="col-sm-3 col-form-label">Vrsta uplate:</label>
                        <div class="col-sm-5">
                            <select class="form-select form-select-sm" name="type_id" id="transaction_type">
                                {% if document.type.id == 1 %}
                                    <option value="1">Avans (gotovinski)</option>
                                    <option value="2">Avans (virmanski)</option>
                                {% elseif document.type.id == 2 %}
                                    <option value="3">Uplata (gotovinska)</option>
                                    <option value="4">Uplata (virmanska)</option>
                                {% endif %}
                            </select>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <label for="date" class="col-sm-3 col-form-label">Datum uplate:</label>
                        <div class="col-sm-5">
                            <input type="date" class="form-control form-control-sm" id="date" name="date"
                                   value="{{ "now"|date("Y-m-d") }}">
                        </div>
                    </div>

                    <div class="row mb-2">
                        <label for="amount" class="col-sm-3 col-form-label">Iznos:</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control form-control-sm" name="amount" id="amount" value="" placeholder="Unesite iznos" />
                        </div>
                    </div>

                    <div class="row mb-2">
                        <label for="note" class="col-sm-3 col-form-label">Beleška:</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control form-control-sm" name="note" id="note" value="" >
                        </div>
                    </div>

                </div>
                <!-- End Modal Body -->

                <div class="modal-footer">
                    <button type="submit" class="btn btn-sm btn-primary" >Evidentiraj uplatu</button>
                </div>

            </form>
        </div>
    </div>
</div>
<!-- End Modal -->

templates/document/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block body %}
    {% include 'document/tools_menu.html.twig' %}
    <div class="col-lg-12 px-2">
        <div class="card mb-4 shadow-sm">
            <div class="card-header p-2">
                <h6 class="m-0 text-dark">Otvaranje novog dokumenta:</h6>
            </div>
            <div class="card-body p-2">
                {% include 'document/form/document.html.twig' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/document/preferences_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block body %}
    {% include 'document/tools_menu.html.twig' %}
    <div class="col-lg-12 px-2">
        {% include 'document/form/preferences_edit.html.twig' %}
    </div>
{% endblock %}

templates/document/tools_menu.html.twig
<div class="col-lg-12 px-2" id="topMeni">
    <div class="card mb-2">
        <div class="card-body py-1 px-2">
            <a href="/documents/new" class="btn btn-sm btn-outline-secondary" title="Otvaranje novog dokumenta!">
                <i class="fas fa-plus"> </i> Dokument
            </a>

            {% if tools_menu.document %}

                {% if tools_menu.view %}
                    <a href="/documents/{{ document.id }}/edit">
                        <button type="button" class="btn btn-sm btn-outline-secondary mx-1"
                                title="Idi na stranicu za izmenu podataka o dokumentu!">
                            <i class="fas fa-edit"> </i>
                        </button>
                    </a>
                {% endif  %}

                {% if tools_menu.edit %}
                    <a href="/documents/{{ document.id }}">
                        <button type="button" class="btn btn-sm btn-outline-secondary mx-1"
                                title="Idi na stranicu za pregled podataka o dokumentu!">
                            <i class="fas fa-eye"> </i>
                        </button>
                    </a>
                {% endif %}

                {# Button trigger modal za dodavanje proizvoda u dokument #}
                <button type="button" class="btn btn-sm btn-outline-secondary mr-1" data-toggle="modal"
                        data-target="#addArticle" title="Dodaj novi proizvod!">
                    <i class="fas fa-plus"> </i> Proizvod
                </button>

                {# Print proforma buttons #}
                <a href="/documents/{{ document.id }}/print" target="_blank">
                    <button type="button" class="btn btn-sm btn-outline-secondary mr-1" title="Štampaj!">
                        <i class="fas fa-print"> </i>
                    </button>
                </a>
                <a href="/documents/{{ document.id }}/print-w" target="_blank">
                    <button type="button" class="btn btn-sm btn-outline-secondary mr-1" title="Štampaj!">
                        <i class="fas fa-print"> </i> w
                    </button>
                </a>

                {# Print dispatch buttons #}
                {% if document.type.id == 2 %}
                    <a href="/documents/{{ document.id }}/print-i" target="_blank">
                        <button type="button" class="btn btn-sm btn-outline-secondary mr-1" title="Štampaj!">
                            <i class="fas fa-print"> </i> I
                        </button>
                    </a>
                    <a href="/documents/{{ document.id }}/print-iw" target="_blank">
                        <button type="button" class="btn btn-sm btn-outline-secondary mr-1" title="Štampaj!">
                            <i class="fas fa-print"> </i> IW
                        </button>
                    </a>
                {% endif %}

                {# Proforma buttons #}
                {% if document.type.id == 1 %}
                    <a href="/documents/{{ document.id }}/export-proforma-to-dispatch">
                        <button type="button" class="btn btn-sm btn-outline-secondary mr-1"
                            {% if document.isArchived %}
                                title="Predračun je arhiviran i nije ga moguće izvesti u otpremnicu" disabled
                            {% else %}
                                title="Izvezi u otpremnicu"
                            {% endif %}
                        >
                            <i class="fas fa-share"> </i> Otpremnica
                        </button>
                    </a>

                    <a href="/projects/new?client_id={{ document.client.id }}&acc_doc_id={{ document.id }}">
                        <button type="button" class="btn btn-sm btn-outline-secondary mr-1" title="Novi projekat!">
                            <i class="fas fa-share"> </i> <i class="fas fa-project-diagram"></i>
                        </button>
                    </a>
                {% endif %}

                {% if user_role_id == 1 %}
                    {% if previous %}
                        <a href="/documents/{{ previous.id }}">
                            <button type="submit" class="btn btn-sm btn-outline-secondary mr-1">
                                <i class="fas fa-arrow-left"> </i>
                            </button>
                        </a>
                    {% endif %}
                    {% if next %}
                        <a href="/documents/{{ next.id }}">
                            <button type="submit" class="btn btn-sm btn-outline-secondary mr-1">
                                <i class="fas fa-arrow-right"> </i>
                            </button>
                        </a>
                    {% endif %}
                {% endif %}

                {# Button trigger modal za evidentiranje transakcije #}
                <button type="button" class="btn btn-sm btn-outline-secondary mr-1" data-toggle="modal"
                        data-target="#addPayment"
                        {% if document.isArchived %}
                            title="Predračun je arhiviran i nije moguće videntiranje transakcija" disabled
                        {% else %}
                            title="Evidentiranje transakcija"
                        {% endif %}
                >
                    <i class="fas fa-hand-holding-usd"></i>
                </button>
                <a href="/documents/{{ document.id }}/transactions">
                    <button type="submit" class="btn btn-sm btn-outline-secondary mr-1" title="Pregled transakcija">
                        <i class="fas fa-eye"></i> <i class="fas fa-dollar-sign"></i>
                    </button>
                </a>
            {% endif %}

            {% if tools_menu.cash_register and not tools_menu.document %}
                <!-- Button trigger modal za cash input -->
                <button type="button" class="btn btn-sm btn-outline-secondary mr-1" data-toggle="modal" data-target="#cashInput" title="Ulaz gotovine u kasu">
                    <i class="fas fa-euro-sign"></i>
                    ->
                    <i class="fas fa-cash-register"></i>
                </button>
                <!-- Button triger modal za cash output -->
                <button type="button" class="btn btn-sm btn-outline-secondary mr-1" data-toggle="modal" data-target="#cashOutput" title="Izlaz gotovine iz kase">
                    <i class="fas fa-cash-register"></i>
                    ->
                    <i class="fas fa-euro-sign"></i>
                </button>

                <!-- Print Button -->
                <a href="/documents/print-daily-cache-report" target="_blank">
                    <button type="submit" class="btn btn-sm btn-outline-secondary mr-1" title="Štampaj!">
                        <i class="fas fa-print"> </i>
                        <i class="fas fa-cash-register"></i>
                    </button>
                </a>
            {% endif %}

        </div>
    </div>

</div>
<!-- /#topMeni -->

templates/document/transactions_by_document.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page_title }}{% endblock %}

{% block body %}
    {% include 'document/tools_menu.html.twig' %}
    <div class="col-lg-12 px-2">
        {% include 'document/table/transactions_by_document_list.html.twig' %}
    </div>
{% endblock %}